app/views/admin.py
from flask import abort
from random import randint
from app.decorators.management_functions import admin_only
from flask import render_template, redirect, url_for, flash
from app.models import User, Emperor, \
    Verification, Invitation, Image, TemporaryEmperor, TemporaryImage, War, TemporaryWar, Architecture, TemporaryArchitecture, Literature, TemporaryLiterature, Artifact, TemporaryArtifact, LogBook, Deletion, Version, CurrentVersion, NewVersion
from app.forms import ChooseForm, LoginForm, ChangePasswordForm, ChangeEmailForm, RegisterForm, RegisterEmail, \
    AdminCodeForm, InvitationCodeForm, AllEmperorForm, WarForm, ArchitectureForm, ImageEditForm, ImageUploadForm, LiteratureForm, ArtifactForm, DeleteForm, ChatForm
from flask_login import current_user, login_user, logout_user, login_required, fresh_login_required
import sqlalchemy as sa
from app.new_file import db
from app.mixed.version_control import to_csv_function_1, to_csv_function_overwrite, to_csv, to_csv_overwrite
from app.mixed.images_handling import save_uploaded_images, approval_add_image, gallery_upload, gallery_upload_addition
from flask import Blueprint
import os
from app.mixed.delete_unused_images import delete_unused_images

admin_bp = Blueprint("admin_bp", __name__)


@admin_bp.route("/admin", endpoint = "admin")
@login_required
@admin_only
def admin():
    # if current_user.role != "Admin":
    #     return redirect(url_for('home'))
    form = ChooseForm()
    q = db.select(User)
    user_lst = db.session.scalars(q)
    #q = db.select(Enrollment)

    return render_template('admin.html', title="Admin", user_lst=user_lst, form=form, choose_form = form)


@admin_bp.route("/admin/manage_additions", methods = ['GET', 'POST'], endpoint = "manage_additions")
@admin_only
@login_required
def manage_additions():
    add_list = db.session.query(TemporaryEmperor).filter(TemporaryEmperor.old_id == -1).all()
    add_list_1 =  db.session.query(TemporaryWar).filter(TemporaryWar.old_id == -1).all()
    add_list_2 = db.session.query(TemporaryArchitecture).filter(TemporaryArchitecture.old_id ==-1).all()
    add_list_3 = db.session.query(TemporaryLiterature).filter(TemporaryLiterature.old_id == -1).all()
    add_list_4 = db.session.query(TemporaryArtifact).filter(TemporaryArtifact.old_id == -1).all()
    return render_template('manage_additions.html', title = "Manage additions", add_list = add_list, add_list_1 = add_list_1, add_list_2 = add_list_2, add_list_3 = add_list_3, add_list_4 = add_list_4)



@admin_bp.route("/admin/manage_edits", methods = ['GET', 'POST'], endpoint = "manage_edits")
@admin_only
@login_required
def manage_edits():
    edit_list = db.session.query(TemporaryEmperor).filter(TemporaryEmperor.old_id != -1).all()
    edit_list_1 = db.session.query(TemporaryWar).filter(TemporaryWar.old_id !=-1).all()
    edit_list_2 = db.session.query(TemporaryArchitecture).filter(TemporaryArchitecture.old_id != -1).all()
    edit_list_3 = db.session.query(TemporaryLiterature).filter(TemporaryLiterature.old_id != -1).all()
    edit_list_4 = db.session.query(TemporaryArtifact).filter(TemporaryArtifact.old_id != -1).all()
    return render_template('manage_edits.html', title = "Manage edits", edit_list = edit_list, edit_list_1 = edit_list_1, edit_list_2 = edit_list_2, edit_list_3 = edit_list_3, edit_list_4 = edit_list_4)


@admin_bp.route('/delete_user', methods=['POST'], endpoint = "delete_user")
@admin_only
def delete_user():
    form = ChooseForm()
    if form.validate_on_submit():
        u = db.session.get(User, int(form.choice.data))
        q = db.select(User).where((User.role == "Admin") & (User.id != u.id))
        first = db.session.scalars(q).first()
        if not first:
            flash("You can't delete your own account if there are no other admin users!", "danger")
        elif u.id == current_user.id:
            logout_user()
            db.session.delete(u)
            db.session.commit()
            return redirect(url_for('home_bp.home'))
        else:
            db.session.delete(u)
            db.session.commit()
    return redirect(url_for('admin_bp.admin'))



@admin_bp.route('/invitation_code/<int:id>', methods=['POST', 'GET'], endpoint = "invitation_code")
@admin_only
def invitation_code(id):
    form = ChooseForm()
    q = db.select(User)
    user_lst = db.session.scalars(q)
    code = randint(10**15, 10**16-1)
    new_data = Invitation(code = code, user_id = id)
    flash("invitation code generated successfully", "success")

    db.session.add(new_data)
    db.session.commit()
    return render_template("admin.html", title = "Admin", user_lst = user_lst, form = form)



@admin_bp.route('/toggle_user_type', methods=['POST'], endpoint = "toggle_user_type")
@admin_only
def toggle_user_type():
    form = ChooseForm()
    if form.validate_on_submit():
        u = db.session.get(User, int(form.choice.data))
        if u.user_type == "user":
            u.user_type = "Authorised"
        elif u.user_type == "Authorised":
            u.user_type = "user"
        db.session.commit()
    return redirect(url_for('admin_bp.admin'))


@admin_bp.route('/admin/de_admin/<int:id>', methods=['POST', 'GET'], endpoint = "de_admin")
@admin_only
@login_required
def de_admin(id):
    if current_user.user_type == "Autocrat":
        form = ChooseForm()
        q = db.select(User)
        user_lst = db.session.scalars(q)
        user = db.session.get(User, id)
        user.role = "Normal"
        flash("User role has now been changed to normal", "success")
        db.session.commit()
    else:
        abort(403)
    return redirect(url_for('admin_bp.admin'))
    #return render_template("admin.html", title = "Admin", user_lst = user_lst, form = form)


@admin_bp.route("/delete_unused_images_/", methods = ["GET", "POST"], endpoint = "delete_unused_images_")
@admin_only
def delete_unused_images_():
    delete_unused_images()
    return redirect(url_for('admin_bp.admin'))

app/views/war.py
from itertools import cycle
from folium.plugins import MarkerCluster
from markupsafe import Markup
from app.decorators.management_functions import admin_only
from flask import render_template, redirect, url_for, flash, request, send_file, send_from_directory,session, jsonify
from app.mixed.emails import verification_email, confirmation_email, approval_email, new_confirmation_email, rejection_email
import folium
from app.models import User, Emperor, \
    Verification, Invitation, Image, TemporaryEmperor, TemporaryImage, War, TemporaryWar, Architecture, TemporaryArchitecture, Literature, TemporaryLiterature, Artifact, TemporaryArtifact, LogBook, Deletion, Version, CurrentVersion, NewVersion
from app.forms import ChooseForm, LoginForm, ChangePasswordForm, ChangeEmailForm, RegisterForm, RegisterEmail, \
    AdminCodeForm, InvitationCodeForm, AllEmperorForm, WarForm, ArchitectureForm, ImageEditForm, ImageUploadForm, LiteratureForm, ArtifactForm, DeleteForm, ChatForm
from flask_login import current_user, login_user, logout_user, login_required, fresh_login_required
from app.new_file import db
from sqlalchemy import or_, and_
from app.mixed.version_control import to_csv_function_1, to_csv_function_overwrite, to_csv, to_csv_overwrite
from app.mixed.images_handling import save_uploaded_images, approval_add_image, gallery_upload, gallery_upload_addition
from flask import Blueprint

war_bp = Blueprint("war_bp", __name__)


@war_bp.route('/wars_selection', endpoint = "wars_selection")
def wars_selection():
    return render_template("wars-selection.html", title = "Type of Wars")


@war_bp.route('/wars_selection/foreign_wars', methods= ['GET', 'POST'], endpoint = "foreign_wars_1")
def foreign_wars_1():
    form = WarForm()
    wars_lst = db.session.query(War).filter(and_(War.war_type == "Foreign War")).all()
    war_map = folium.Map(location=[41.008333, 28.98], zoom_start=3)

    colors = cycle(['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred',
                    'beige', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple',
                    'white', 'pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray'])
    names = sorted({ war.war_name for war in wars_lst if war.war_name})
    war_colors = {name: next(colors) for name in names}
    cluster = MarkerCluster().add_to(war_map)

    for war in wars_lst:
        if war.latitude is not None and war.longitude is not None:
            color = war_colors.get(war.war_name, 'gray')
            folium.Marker(location= [war.latitude, war.longitude],
                          tooltip=war.title,
                          popup=folium.Popup(f"<b>{war.title}</b><br>{war.war_name}<br>{war.dates}", max_width=300),
                          icon=folium.Icon(color=color)
            ).add_to(cluster)
    war_html = war_map._repr_html_()

    return render_template('foreign_war_1.html', title = "Foreign Wars", wars_lst = wars_lst, war_html =Markup(war_html) , form_open = False, new_form = form)


@war_bp.route('/wars_selection/civil_wars', methods= ['GET', 'POST'], endpoint = "civil_wars")
def civil_wars():
    form = WarForm()
    wars_lst = db.session.query(War).filter(War.war_type == "Civil War").all()
    war_map = folium.Map(location=[41.008333, 28.98], zoom_start=3)

    colors = cycle(['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred',
                    'beige', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple',
                    'white', 'pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray'])
    names = sorted({war.war_name for war in wars_lst if war.war_name})
    war_colors = {name: next(colors) for name in names}
    cluster = MarkerCluster().add_to(war_map)

    for war in wars_lst:
        if war.latitude is not None and war.longitude is not None:
            color = war_colors.get(war.war_name, 'gray')
            folium.Marker(location=[war.latitude, war.longitude],
                          tooltip=war.title,
                          popup=folium.Popup(f"<b>{war.title}</b><br>{war.war_name}<br>{war.dates}", max_width=300),
                          icon=folium.Icon(color=color)
                          ).add_to(cluster)
    war_html = war_map._repr_html_()
    return render_template('civil_wars.html', title = "Civil Wars", wars_lst = wars_lst, war_html =Markup(war_html) , form_open = False, new_form = form)


@war_bp.route("/admin/manage_additions/add_info_war/<int:id>", methods = ['GET', 'POST'], endpoint = "add_info_war")
@admin_only
@login_required
def add_info_war(id):
    war_add = db.session.get(TemporaryWar, id)
    return render_template("edit_add_info_war.html", war = war_add, title = "Preview")


@war_bp.route("/manage_edits_additions_users/war_info_edit_user/<int:id>", methods = ['GET', 'POST'], endpoint = "war_info_edit_user")
@login_required
def war_info_edit_user(id):
    war_first = db.session.get(TemporaryWar, id)
    form = WarForm(obj=war_first)
    form.edit.data = war_first.id
    return render_template("war_info_edit_user.html",war = war_first, form_open = False, title="War edit/addition information", new_form=form)



@war_bp.route("/admin/manage_edits/edit_info_war/<int:id>", methods = ['GET', 'POST'], endpoint = "edit_info_war")
@admin_only
@login_required
def edit_info_war(id):
    war_edit = db.session.get(TemporaryWar, id)
    return render_template("edit_add_info_war.html", war = war_edit, title = "Preview")


@war_bp.route("/delete_wars_/<int:id>", methods = ['GET', 'POST'], endpoint = "delete_wars_")
@admin_only
def delete_wars_(id):
    delete_wars__ = db.session.get(War, id)
    to_csv(current_user.username, delete_wars__.title)
    if delete_wars__.war_type == "Civil War":
        db.session.delete(delete_wars__)
        if delete_wars__.images:
            delete_images_ = delete_wars__.images[0]
            db.session.delete(delete_images_)
        delete_log = LogBook(original_id=id, title=delete_wars__.title,
                             username=current_user.username)
        db.session.add(delete_log)
        db.session.commit()
        to_csv_overwrite(current_user.username)
        return redirect(url_for("war_bp.civil_wars"))
    elif delete_wars__.war_type == "Foreign War":
        db.session.delete(delete_wars__)
        if delete_wars__.images:
            delete_images_ = delete_wars__.images[0]
            db.session.delete(delete_images_)
        delete_log = LogBook(original_id=id, title=delete_wars__.title,
                             username=current_user.username)
        db.session.add(delete_log)
        db.session.commit()
        to_csv_overwrite(current_user.username)
        return redirect(url_for("war_bp.foreign_wars_1"))
    return redirect(request.referrer)


@war_bp.route("/wars_selection/war_info/<int:id>", methods=['GET','POST'], endpoint = "war_info_foreign_1")
def war_info_foreign_1(id):
    #m_e = db.session.query(Emperor).filter_by(dynasty = 'Macedonian').all()
    war_first = db.session.get(War, id)
    form = WarForm(obj=war_first)
    form.edit.data = war_first.id
    return render_template("war_info.html", war = war_first, title = "Battle information", new_form = form, form_open = False)


@war_bp.route("/add_new_war_1/<string:war_category>", methods = ['POST', 'GET'], endpoint = "add_new_war_1")
@login_required
def add_new_war_1(war_category):
    form = WarForm()
    if war_category == "foreign":
        war_type = "Foreign War"
        template = "foreign_war_1.html"
        redirect_ = "war_bp.foreign_wars_1"
        page_title = "Foreign War"
    else:
        war_type = "Civil War"
        template = "civil_wars.html"
        redirect_ = "war_bp.civil_wars"
        page_title = "Civil War"
    wars_lst = db.session.query(War).filter(War.war_type == war_type).all()
    war_map = folium.Map(location=[41.008333, 28.98], zoom_start=3)

    colors = cycle(['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred',
                    'beige', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple',
                    'white', 'pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray'])
    names = sorted({war.war_name for war in wars_lst if war.war_name})
    war_colors = {name: next(colors) for name in names}
    cluster = MarkerCluster().add_to(war_map)
    for war in wars_lst:
        if war.latitude is not None and war.longitude is not None:
            color = war_colors.get(war.war_name, 'gray')
            folium.Marker(location=[war.latitude, war.longitude],
                          tooltip=war.title,
                          popup=folium.Popup(f"<b>{war.title}</b><br>{war.war_name}<br>{war.dates}", max_width=300),
                          icon=folium.Icon(color=color)
                          ).add_to(cluster)
    war_html = war_map._repr_html_()
    if form.validate_on_submit() and int(form.edit.data) == -1:
        if current_user.role == "Admin":
            column_names = [column.name for column in War.__table__.columns if column.name != "id"]
            new_war = War(
                **{column: getattr(form, column).data for column in column_names if hasattr(form, column)})
            to_csv(current_user.username, new_war.title)
            db.session.add(new_war)
            db.session.commit()
            new_log_4 = LogBook(original_id=new_war.id, title=new_war.title, username=current_user.username)
            db.session.add(new_log_4)
            # print(form.portrait.data.filename)
            if form.image.data:
                save_uploaded_images(file=form.image.data, obj_id=new_war.id, field_name="war_id",
                                     model=Image)
                db.session.commit()
            to_csv_overwrite(current_user.username)
            return redirect(url_for(redirect_))
        else:
            column_names = [column.name for column in TemporaryWar.__table__.columns if column.name != "id"]
            temporary_war_edit = TemporaryWar(

app/templates/add_info_emperor.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}
{% block head_extra %}
<style>
    .circle-button{
    display: inline-block;
    width: 210px;
    height: 210px;
    overflow: hidden;
    border-radius: 50%;
    border: 2px solid transparent;
    }

    .small-image{
    max-width:150px;
    height:auto;
    }
    .circle-button img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
    }

    .button-label {
    text-align: center;
    margin-bottom: 0.5rem;
    font-size: 1rem;
    color: #333;
    }

    .button-column {
    display: flex;
    flex-direction: column;
    align-items: center;}

    .button-row{
    display: flex;
    justify-content: space-between;
    margin-bottom: 1.5rem;
    flex-wrap: wrap;
    gap: 1rem;
    }

    .button-row.centered{
    justify-content: center;
    gap: 2rem;
    }
    .latin-heading_2 {
    font-family: 'Cinzel', serif;
    font-size: 1rem;
    color: #000000;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-weight: bold;
    }
    .latin-heading_3 {
    font-family: 'Cinzel', serif;
    color: #000000;
    letter-spacing: 1px;
    text-transform: none;
    font-weight: bold;
    font-size: 1.3rem;
    }
    .greek-heading_2 {
    font-family: 'GFS Didot', serif;
    font-size: 1rem;
    color: #000000;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-weight: bold;
    }

    .table {
  background-color: transparent !important;}

.table td,
.table th {
  background-color: transparent !important;
  border: 1px solid transparent;}

.col-lg-9 {
  margin-top: 0 !important;
}


    .background-container {
    background-image: url("{{url_for('static', filename = 'images/parchment_color.jpg')}}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    min-height:100vh;
    display: flex;
    flex-direction:column;
    padding: 0.5rem;
    }

    .background-container h1 {
    margin: 20px;
    }


    @media (max-width: 768px) {
    .button-row{
    flex-direction: column;
    align-items: center;
    gap: 2rem;
    }

    .coin-row{
    flex-direction: column;
    align-items: center;
    gap: 2rem;
    }

    .circle-button {
    width:160px;
    height: 160px;
    }

    .greek-heading_2,
    .latin-heading_2 {
    font-size: 0.8rem;
    text-align: center;
    }
    .button-label {
    text-align: center;
    margin-bottom: 0.8rem;
    }

    .centered-line {
    width:100%;
    max-width: 700px;
    text-align: center;
    font-size: 2.6rem;
    margin: 1rem 0 0.5rem;
    }


     .coin-row-and-text{
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    margin: 0 auto 1rem;
    padding: 0 1rem;
    box-sizing: border-box;
    flex-wrap: wrap;
    }

    .coin-row{
    display:flex;
    gap: 2rem;
    justify-content: center;
    }
    .side-text {
    width: 170px;
    }

    .side-text p{
    margin: 0.25rem 0;
    line-height: 1.2;
    }

    .left {
    text-align: left;
    }

    .right {
    text-align: right;
    }
    }
    .container-split{
    display: flex;
    justify-content: space-between;
    margin: 2rem 10%;
    border-top: 0px solid #000000;
    border-bottom: 0px solid #000000;
    padding-top: 2rem;
    gap: 2rem;
    flex-wrap: wrap;
    }
    .image-left-wrap {
    float: left;
    width: 600px;
    height: auto;
    margin: 0 1.5rem 1rem 0;
    box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.15);
}
    .container-left {
    flex:1;
    text-align: center;
    }

    .divider {
    width: 1.5px;
    background-color: #000000;
    margin: 0;
    }

    .container-right {
    flex:1;
    text-align: left;
    line-height:1.5;
    }

    .text-wrap-container {
    max-width: 80%;
    margin: 2rem auto;
    font-size: 1rem;
    line-height: 1.6;
    color: #000;
    text-align: justify;
    }

    .desktop-margins_3{
    text-align: left;
    margin-left: 15rem;
    }

    @media (max-width: 800px) {
    .desktop-margins_3{
    margin-left: 0rem;
    text-align:left;
    }
    }

@media (max-width: 800px) {
    .image-left-wrap {
        float: none;
        display: block;
        margin: 1rem auto;
        width: 90%;
    }
}

</style>
{% endblock %}

{% block flash_messages %}{% endblock %}

{% block content %}
<div class="background-container">
    <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
    <h1 style="text-align: center; margin-bottom: 1rem;">
        <span class="greek-heading_2" style="display: block; font-size: 2rem;">{{emperor_add.in_greek}}</span>
    <span class="latin-heading_2" style="display: block; font-size: 2rem;">{{emperor_add.title}}</span>
    </h1>
    <div style="text-align: center; margin-bottom: 0rem;">
        <span class="latin-heading_3"><strong>Born:</strong>{{emperor_add.birth}}</span>
    </div>
    <div style="text-align: center; margin-bottom: 0.2rem;">
        <span class="latin-heading_3"><strong>Died:</strong>{{emperor_add.death}}</span>
    </div>
     <div style="text-align: center; margin-bottom: 0rem;">
        <span class="latin-heading_3"><strong>Reign:</strong>{{emperor_add.reign}}</span>
    </div>

        <div class="text-wrap-container latin-heading_new" >{% if emperor_add.temporary_images %}
            <img src="{{emperor_add.temporary_images[0].url}}" alt = "{{emperor_add.temporary_images[0].filename}}"  class="image-left-wrap">
            {% else %}
            No image
            {% endif %}
    <p>        {{ emperor_add.life.replace('\n', '<br>')| safe }}</p>

    </div>

    <div class="latin-heading_new desktop-margins" style=" text-align: left; line-height: 1.6;">
      References: <br>{{ emperor_add.references.replace('\n', '<br>')| safe }}
    </div>


</div>
{% endblock %}

app/templates/admin.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}




{% block head_extra %}

<style>
    .latin-heading_2 {
    font-family: 'Cinzel', serif;
    font-size: 1rem;
    color: #000000;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-weight: bold;
    }
    .latin-heading_3 {
    font-family: 'Cinzel', serif;
    font-size: 1rem;
    color: #000000;
    letter-spacing: 1px;
    text-transform: none;
    font-weight: bold;
    }
    .greek-heading_2 {
    font-family: 'GFS Didot', serif;
    font-size: 1rem;
    color: #000000;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-weight: bold;
    }

    .background-container {
    background-image: url("{{url_for('static', filename = 'images/parchment_color.jpg')}}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    min-height:100vh;
    display: flex;
    width: 100%;
    flex-direction:column;
    justify-content: flex-start;
    align-items: stretch;
    padding: 3rem 2rem 0rem 2rem;
    }
        .table {
  background-color: transparent !important;}

.table td,
.table th {
  background-color: transparent !important;
  border: 1px solid transparent;}


</style>
{% endblock %}

{% block flash_messages %}{% endblock %}

{% block content %}
<div class="background-container">

<div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

<h1 class="latin-heading_3">Admin</h1>
<div class="col-lg-12">
            <div class="table-responsive">
<table class="table" style="background-color: transparent;">
    <thead>
        <tr>
            <th class="latin-heading_3">ID</th>
            <th class="latin-heading_3">Username</th>
            <th class="latin-heading_3">Email</th>
            <th class="latin-heading_3">Role</th>
            <th class="latin-heading_3">User type</th>
            <th class="latin-heading_3">Delete user</th>
            <th class="latin-heading_3">Grant/remove authorisation</th>
            <th class="latin-heading_3">Promote/demote user</th>
        </tr>
    </thead>
    {% for user in user_lst %}
<tr>
    <td class="latin-heading_3">{{ user.id }}</td>
    <td class="latin-heading_3">{{ user.username }}</td>
    <td class="latin-heading_3">{{ user.email }}</td>
    <td class="latin-heading_3">{{ user.role }}</td>
    <td class="latin-heading_3">{{ user.user_type }}</td>

    <td>
        {% if current_user.user_type == "Autocrat" and user.user_type != "Autocrat" %}
        <form action="{{ url_for('admin_bp.delete_user') }}" method="post">
            {{ form.csrf_token() }}
            {{ form.choice(value=user.id) }}
            <button class="btn" type="submit"><i class="bi bi-trash"></i></button>
        </form>
        {% elif current_user.user_type != "Autocrat" and user.role == "Normal" %}
        <form action="{{ url_for('admin_bp.delete_user') }}" method="post">
            {{ form.csrf_token() }}
            {{ form.choice(value=user.id) }}
            <button class="btn" type="submit"><i class="bi bi-trash"></i></button>
        </form>
        {% endif %}
    </td>

    <td>
        {% if user.role == "Normal" %}
        <form action="{{ url_for('admin_bp.toggle_user_type') }}" method="post">
            {{ form.csrf_token() }}
            {{ form.choice(value=user.id) }}
            <button class="btn" type="submit">
                {% if user.user_type == "Authorised" %}
                <i class="bi bi-toggle-on"> Remove Authorisation</i>
                {% else %}
                <i class="bi bi-toggle-off"> Grant Authorisation</i>
                {% endif %}
            </button>
        </form>
        {% endif %}
    </td>

    <td>
        {% if user.role == "Normal" %}
        <form action="{{ url_for('admin_bp.invitation_code', id=user.id) }}" method="get" style="display:inline;">
            <button type="submit" class="btn" title="invitation code">
                <i class="bi bi-arrow-up-circle-fill"></i>
            </button>
        </form>
        {% endif %}
    </td>

    <td>
        {% if user.role == "Admin" and user.id != current_user.id and current_user.user_type == "Autocrat" %}
        <form action="{{ url_for('admin_bp.de_admin', id=user.id) }}" method="get" style="display:inline;">
            <button type="submit" class="btn" title="demote">
                <i class="bi bi-arrow-down-circle-fill"></i>
            </button>
        </form>
        {% endif %}
    </td>
</tr>
{% endfor %}


</table>
                </div>
    <h3 class="mt-5 latin-heading_new" style="font-size: 1.5rem;">Manage account</h3>
    <ul>
        <li class="latin-heading_new" style="font-size: 1.5rem;"><a href="{{ url_for('admin_bp.manage_edits') }}">Manage Edits</a></li>
    </ul>
    <ul>
        <li class="latin-heading_new" style="font-size: 1.5rem;"><a href="{{ url_for('admin_bp.manage_additions') }}">Manage Additions</a></li>
    </ul>
    <ul>
        <li class="latin-heading_new" style="font-size: 1.5rem;"><a href="{{ url_for('version_control_bp.versions_') }}">Version Control</a></li>
    </ul>
    <h3 class="mt-3 latin-heading_new" style="font-size: 1.5rem;">Delete unneeded images</h3>

    <div style="text-align: left;">
    <a href="{{url_for('admin_bp.delete_unused_images_')}}" class="btn btn-dark" style="background-color: transparent">Delete Redundant Images </a>
        </div>
</div>
</div>



{% endblock %}

app/templates/rejection.sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New request is rejected</title>
</head>
<body>
<p>Hello!</p>
<p>Sorry! Your new addition/editing request about {{title}} has been rejected .</p>
</body>
</html>